language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - libboost-all-dev
            - libgflags-dev
            - libopencv-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="brew install eigen gflags && brew install opencv3 --with-python3 || true"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user opencv-python

before_script:
  - scripts/build.sh

script:
  - scripts/run_tests.sh
