language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - libboost-all-dev
            - libgflags-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="brew install gcc5 boost cmake eigen gflags opencv3 && CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - scripts/build.sh

script:
  - scripts/run_tests.sh
