if (MSVC)
    find_path(PNG_INCLUDE_DIRS png.h PATHS ${LIBPNG_ROOT}/include)
    set(LIBPNG_LIB_DIR ${LIBPNG_ROOT}/lib/Win32/v110/static/${CONFIGURATION})
    find_library(PNG_LIBRARIES  NAMES "libpng15.lib" libpng PATHS ${LIBPNG_LIB_DIR})
    if (PNG_INCLUDE_DIRS)
        set(PNG_FOUND True)
    endif()
else()
    find_package(PNG REQUIRED)
endif()
