# TODO: better not to change the module path and include all the other
# Find*.cmake modules shipped with g2o
set(G2O_ROOT ${THIRDPARTY_SOURCE_DIR}/installdir)
include(${PROJECT_SOURCE_DIR}/cmake/FindG2O.cmake)

if(VERBOSE)
    message(STATUS "g2o core library: ${G2O_CORE_LIBRARY}")
    message(STATUS "g2o types slam3d library: ${G2O_TYPES_SLAM3D}")
    message(STATUS "g2o stuff library: ${G2O_STUFF_LIBRARY}")
    message(STATUS "g2o solver library: ${G2O_SOLVER_CSPARSE}")
endif()

mark_as_advanced(
    G2O_CLI_LIBRARY
    G2O_CLI_LIBRARY_DEBUG
    G2O_CORE_LIBRARY
    G2O_CORE_LIBRARY_DEBUG
    G2O_INCLUDE_DIR
    G2O_SOLVER_CHOLMOD
    G2O_SOLVER_CHOLMOD_DEBUG
    G2O_SOLVER_CSPARSE
    G2O_SOLVER_CSPARSE_DEBUG
    G2O_SOLVER_CSPARSE_EXTENSION
    G2O_SOLVER_CSPARSE_EXTENSION_DEBUG
    G2O_SOLVER_DENSE
    G2O_SOLVER_DENSE_DEBUG
    G2O_SOLVER_EIGEN
    G2O_SOLVER_EIGEN_DEBUG
    G2O_SOLVER_PCG
    G2O_SOLVER_PCG_DEBUG
    G2O_SOLVER_SLAM2D_LINEAR
    G2O_SOLVER_SLAM2D_LINEAR_DEBUG
    G2O_SOLVER_STRUCTURE_ONLY
    G2O_SOLVER_STRUCTURE_ONLY_DEBUG
    G2O_STUFF_LIBRARY
    G2O_STUFF_LIBRARY_DEBUG
    G2O_TYPES_DATA
    G2O_TYPES_DATA_DEBUG
    G2O_TYPES_ICP
    G2O_TYPES_ICP_DEBUG
    G2O_TYPES_SBA
    G2O_TYPES_SBA_DEBUG
    G2O_TYPES_SCLAM2D
    G2O_TYPES_SCLAM2D_DEBUG
    G2O_TYPES_SIM3
    G2O_TYPES_SIM3_DEBUG
    G2O_TYPES_SLAM2D
    G2O_TYPES_SLAM2D_DEBUG
    G2O_TYPES_SLAM3D
    G2O_TYPES_SLAM3D_DEBUG
)
