find_package(PythonInterp 3.5)

if(PYTHONINTERP_FOUND)
    set(PYTHON_VERSION_MAJOR_MINOR "${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}")
    find_package(PythonLibs "${PYTHON_VERSION_MAJOR_MINOR}.${PYTHON_VERSION_PATCH}" EXACT)
    if(PYTHONLIBS_FOUND)
        message("Found Python includes: ${PYTHON_INCLUDE_DIR}")
        message("Found Python libs: ${PYTHON_LIBRARY}")
    else()
        message(WARNING "Did not find PythonLibs")
    endif(PYTHONLIBS_FOUND)
else()
    message(WARNING "Could not find Python interpreter")
endif(PYTHONINTERP_FOUND)
